# ベースイメージ
FROM python:3.11-bullseye

ENV PYTHONUNBUFFERED 1

# 作業ディレクトリの設定
WORKDIR /django_app

# 依存関係ファイルのコピー
COPY ./backend/pyproject.toml /django_app/
COPY ./backend/poetry.lock /django_app/

# 必要なパッケージをインストール
RUN pip install --upgrade pip && pip install pipx && pipx install poetry && export PATH=$PATH:/root/.local/bin && poetry install --no-root

# アプリケーションのソースコードをコピー
COPY ./backend/django_app /django_app/

# 開発サーバーを起動
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]