# Generated by Django 4.2.9 on 2024-02-25 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("recipe_name", models.CharField(max_length=128)),
                ("data_url", models.URLField(blank=True)),
                ("memo", models.TextField(blank=True)),
                ("image_1", models.ImageField(blank=True, upload_to="images/")),
                ("image_2", models.ImageField(blank=True, upload_to="images/")),
                ("image_3", models.ImageField(blank=True, upload_to="images/")),
                ("main_tag", models.CharField(blank=True, max_length=128)),
                ("genre_tag", models.CharField(blank=True, max_length=128)),
                ("jitan_tag", models.BooleanField(default=False)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
