# Generated by Django 4.2.9 on 2024-02-20 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="image_url",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="recipestag",
            name="recipe_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_tags",
                to="api.recipes",
            ),
        ),
        migrations.AlterField(
            model_name="recipestag",
            name="tag_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tag_recipes",
                to="api.tags",
            ),
        ),
    ]
